### ISSUE TITLE
using zswap and zram together

### ISSUE THREAD

**Issue by iaacornus** [devangshekhawat/Fedora-39-Post-Install-Guide#4]
greetings,

thank you for a nice tutorial article, it is the most comprehensive and best i've read, thus far. however, I've notice in your article that u advised to use zswap and zram together. [zram is already working out of the box in fedora,](https://fedoraproject.org/wiki/Changes/SwapOnZRAM) and u recommended turning on the zswap module without disabling the other. since as far as im aware those two are not recommended to run at the same time. enabling both can result in wasted cpu cycles since it will result in redundant compression of the same pages.

moreover, zswap is also known to be buggy and lead to kernel stack traces and zombie/hung process, as reported anecdotically. personally, im using zram, but i think if u will recommend enabling zswap, u should also have them disable zram to avoid cpu drawbacks.

regards.

**Comment by devangshekhawat** [comment]
Thanks for your contribution.
Removing zswap entirely now.
I used to use arch linux and was pretty accustomed to having a swap partition but upon further research zram just seems superior and compatible with more systems overall.
