### ISSUE TITLE
turning off mitigations

### ISSUE THREAD

**Issue by iaacornus** [devangshekhawat/Fedora-39-Post-Install-Guide#5]
greetings, again.

turning off mitigations, albeit the fact that it _might_ increase the performance of ur cpu if it is old[^1], can open up some vulnerabilities and decrease the security of ur system. mitigations were added to linux kernel as a workaround against various attacks (e.g. zombieload attack), unfortunately it comes with its compromises, hence disabling the migitations to gain back the performance loss can give its security drawback

> [Unfortunately there is no safe and secure way around the performance-penalties](https://linuxreviews.org/HOWTO_make_Linux_run_blazing_fast_(again)_on_Intel_CPUs)

hence, i think the readers should be aware of its consequences, like just keeping a note before disabling it. 

[^1]: it was found out that disabling mitigations do not give any noticeable performance difference in 10th gen intel cpus and higher.

regards.

**Comment by iaacornus** [comment]
ive made a pr that includes a brief info about the mitigation module and a note, i hope it does not come as dick move, since i think the decision should be made with full information presenting the security drawbacks over the performance gains, thanks.

**Comment by devangshekhawat** [comment]
Reviewed and merged the pull request. 
Thanks a lot for the contribution!
